/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameCidadeCadastro.java
 *
 * Created on Sep 29, 2008, 5:05:38 PM
 */
package org.ai.forms.ambiente.cidades;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import org.ai.bo.ambiente.Cidade;
import org.ai.bo.ambiente.Estado;
import org.ai.bo.ambiente.Regiao;

/**
 *
 * @author Edison
 */
public class FrameCidadeCadastro extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private List<Estado> listEstados;
    private List<Regiao> listRegioes;
    private Estado estado;
    private Regiao regiao;
    private DefaultComboBoxModel modelEstados;
    private DefaultComboBoxModel modelRegioes;



    public FrameCidadeCadastro() {
        initComponents();
        updateComboEstados();
        updateComboRegioes();
    }
    
    public FrameCidadeCadastro(Estado estado) {
        initComponents();
        this.estado = estado;
        String[] data = new String[]{estado.getNome()};
        modelEstados = new DefaultComboBoxModel(data);
        cmbEstado.setModel(modelEstados);
        cmbEstado.revalidate();
        cmbEstado.setEnabled(false);
        updateComboRegioes();
    }
    
    public FrameCidadeCadastro(Regiao regiao) {
        initComponents();
        this.regiao = regiao;
        String[] data = new String[]{regiao.getNome()};
        modelRegioes = new DefaultComboBoxModel(data);
        cmbRegiao.setModel(modelRegioes);
        cmbRegiao.revalidate();
        cmbRegiao.setEnabled(false);
        updateComboEstados();
    }

    private void updateListEstados() {
        listEstados = Estado.findAll();
        String[] data = new String[listEstados.size() + 1];
        data[0] = "Selecione um Estado...";
        for (int i = 0; i < listEstados.size(); i++) {
            data[i + 1] = listEstados.get(i).getNome();
        }
        modelEstados = new DefaultComboBoxModel(data);
    }

    private void updateComboEstados() {
        updateListEstados();
        cmbEstado.setModel(modelEstados);
        cmbEstado.revalidate();
        estado = null;
    }

    private void updateListRegioes() {
        listRegioes = Regiao.findAll();
        String[] data = new String[listRegioes.size() + 1];
        data[0] = "Selecione uma Região...";
        for (int i = 0; i < listRegioes.size(); i++) {
            data[i + 1] = listRegioes.get(i).getNome();
        }
        modelRegioes = new DefaultComboBoxModel(data);
    }

    private void updateComboRegioes() {
        updateListRegioes();
        cmbRegiao.setModel(modelRegioes);
        cmbRegiao.revalidate();
        regiao = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        cmbRegiao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setTitle("Cadastro de Cidade");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/location_16.png"))); // NOI18N

        jLabel1.setText("Nome");

        jLabel2.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        cmbRegiao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRegiaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Região");

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/location_add_16.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNomeCidade))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbRegiao, 0, 170, Short.MAX_VALUE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnCadastrar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        if (cmbEstado.getSelectedIndex() != 0) {
            estado = listEstados.get(cmbEstado.getSelectedIndex() - 1);
        } else {
            estado = null;
        }
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void cmbRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRegiaoActionPerformed
        if (cmbRegiao.getSelectedIndex() != 0) {
            regiao = listRegioes.get(cmbRegiao.getSelectedIndex() - 1);
        } else {
            regiao = null;
        }
    }//GEN-LAST:event_cmbRegiaoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (estado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado");
        } else if (regiao == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma Região");
        } else {
            int resposta = JOptionPane.showConfirmDialog(this, "Confirma cadastro da cidade " + txtNomeCidade.getText() + "?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (resposta == JOptionPane.YES_OPTION) {
                Cidade cidade = new Cidade();
                cidade.setNome(txtNomeCidade.getText());
                cidade.setEstado(estado);
                cidade.setRegiao(regiao);
                boolean created = cidade.create();
                if (created) {
                    JOptionPane.showMessageDialog(this, "Cidade " + cidade.getNome() + " cadastrada com sucesso");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar a Cidade " + cidade.getNome());
                }
                dispose();
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbRegiao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNomeCidade;
    // End of variables declaration//GEN-END:variables
}
