/*
 * FrameRamoAtividadeManutencao.java
 *
 * Created on October 5, 2008, 10:51 PM
 */
package org.ai.forms.ambiente.ramos;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableModel;

import org.ai.bo.ambiente.Estabelecimento;
import org.ai.bo.ambiente.RamoAtividade;
import org.ai.forms.FormMenuPrincipal;
import org.ai.forms.ambiente.cidades.FrameCidadeCadastro;
import org.ai.forms.ambiente.estabelecimentos.FrameEstabelecimentoCadastro;
import org.ai.forms.ambiente.estabelecimentos.FrameEstabelecimentoManutencao;
import org.ai.forms.utils.ColumnResizer;

/**
 *
 * @author  Edison
 */
public class FrameRamoAtividadeManutencao extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;

    private RamoAtividade ramo;
    private List<Estabelecimento> listEstabelecimentosRamo;
    private DefaultTableModel modelEstabelecimentosRamo;
    private FormMenuPrincipal formPrincipal;
    
    /** Creates new form FrameRamoAtividadeManutencao
     * @param formPrincipal
     * @param idRamo 
     */
    public FrameRamoAtividadeManutencao(FormMenuPrincipal formPrincipal, int idRamo) {
        initComponents();
        this.formPrincipal = formPrincipal;
        this.ramo = RamoAtividade.find(idRamo);
        txtNome.setText(ramo.getNome());
        updateTableEstabelecimentosRamo();
    }

    public void updateTableEstabelecimentosRamo() {
        updateListEstabelecimentosRamo();
        tableEstabelecimentos.setModel(modelEstabelecimentosRamo);
        tableEstabelecimentos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableEstabelecimentos.setRowSelectionAllowed(true);
        tableEstabelecimentos.setColumnSelectionAllowed(false);
        ColumnResizer.adjustColumnPreferredWidths(tableEstabelecimentos);
        tableEstabelecimentos.revalidate();
        lblTotalEstabelecimentos.setText(Integer.toString(listEstabelecimentosRamo.size()));
    }

    private void updateListEstabelecimentosRamo() {
        listEstabelecimentosRamo = ramo.getEstabelecimentos();
        String[] collumnNames = new String[]{"Nome", "Estado","Cidade"};
        String[][] data = new String[listEstabelecimentosRamo.size()][];
        for (int i = 0; i < listEstabelecimentosRamo.size(); i++) {
            data[i] = new String[]{
                        listEstabelecimentosRamo.get(i).getNome(),
                        listEstabelecimentosRamo.get(i).getCidade().getEstado().getNome(),
                        listEstabelecimentosRamo.get(i).getCidade().getNome()
                    };
        }
        modelEstabelecimentosRamo = new DefaultTableModel(data, collumnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnInserirEstabelecimento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEstabelecimentos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblTotalEstabelecimentos = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manutenção de Ramo de Atividade");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/activity_16.png"))); // NOI18N

        jLabel1.setText("Nome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ramo", jPanel1);

        btnInserirEstabelecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/industry_add_16.png"))); // NOI18N
        btnInserirEstabelecimento.setText("Inserir");
        btnInserirEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirEstabelecimentoActionPerformed(evt);
            }
        });

        tableEstabelecimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEstabelecimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEstabelecimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEstabelecimentos);

        jLabel2.setText("Total de Estabelecimentos:");

        lblTotalEstabelecimentos.setText("total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInserirEstabelecimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalEstabelecimentos)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirEstabelecimento)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalEstabelecimentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estabelecimentos", jPanel2);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/activity_write_16.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/activity_remove_16.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void btnInserirEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirEstabelecimentoActionPerformed
    FrameEstabelecimentoCadastro frame = new FrameEstabelecimentoCadastro(ramo);
    formPrincipal.getDesktopPane().add(frame);
    frame.setLocation((int) this.getBounds().getX(), (int) this.getBounds().getY() + this.getHeight());
    frame.setVisible(true);
    frame.addInternalFrameListener(new InternalFrameListener() {
        public void internalFrameOpened(InternalFrameEvent e) {}
        public void internalFrameClosing(InternalFrameEvent e) {}
        public void internalFrameClosed(InternalFrameEvent e) {
            ramo.setEstabelecimentos(RamoAtividade.find(ramo.getId()).getEstabelecimentos());
            updateTableEstabelecimentosRamo();
        }
        public void internalFrameIconified(InternalFrameEvent e) {}
        public void internalFrameDeiconified(InternalFrameEvent e) {}
        public void internalFrameActivated(InternalFrameEvent e) {}
        public void internalFrameDeactivated(InternalFrameEvent e) {}
    });
}//GEN-LAST:event_btnInserirEstabelecimentoActionPerformed

private void tableEstabelecimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEstabelecimentosMouseClicked
    if (tableEstabelecimentos.getSelectedRow() >= 0) {
        Estabelecimento estabelecimento = listEstabelecimentosRamo.get(tableEstabelecimentos.getSelectedRow());
        FrameEstabelecimentoManutencao frame = new FrameEstabelecimentoManutencao(formPrincipal,estabelecimento.getId());
        formPrincipal.getDesktopPane().add(frame);
        frame.setLocation((int) this.getBounds().getX(), (int) this.getBounds().getY() + this.getHeight());
        frame.setVisible(true);
        frame.addInternalFrameListener(new InternalFrameListener() {
                public void internalFrameOpened(InternalFrameEvent e) {}
                public void internalFrameClosing(InternalFrameEvent e) {}
                public void internalFrameClosed(InternalFrameEvent e) {
                    ramo.setEstabelecimentos(RamoAtividade.find(ramo.getId()).getEstabelecimentos());
                    updateTableEstabelecimentosRamo();
                }
                public void internalFrameIconified(InternalFrameEvent e) {}
                public void internalFrameDeiconified(InternalFrameEvent e) {}
                public void internalFrameActivated(InternalFrameEvent e) {}
                public void internalFrameDeactivated(InternalFrameEvent e) {}
            });
    }
}//GEN-LAST:event_tableEstabelecimentosMouseClicked

private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    int resposta = JOptionPane.showConfirmDialog(this, "Salvar alterações do Ramo de Atividade " + ramo.getNome() + "?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (resposta == JOptionPane.YES_OPTION) {
        ramo.setNome(txtNome.getText());
        boolean updated = ramo.update();
        if (updated) {
            JOptionPane.showMessageDialog(this, "Ramo " + ramo.getNome() + " salvo com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar Ramo " + ramo.getNome());
        }
        dispose();
    }
}//GEN-LAST:event_btnSalvarActionPerformed

private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    int resposta = JOptionPane.showConfirmDialog(this, "Confirma exclusão do Ramo de Atividade " + ramo.getNome() + "?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if (resposta == JOptionPane.YES_OPTION) {
        boolean deleted = ramo.delete();
        if (deleted) {
            JOptionPane.showMessageDialog(this, "Ramo de Atividade " + ramo.getNome() + " excluido com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir ramo " + ramo.getNome());
        }
        dispose();
    }
}//GEN-LAST:event_btnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnInserirEstabelecimento;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTotalEstabelecimentos;
    private javax.swing.JTable tableEstabelecimentos;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
