/*
 * FrameRedeNeuralConsulta.java
 *
 * Created on October 14, 2008, 4:47 PM
 */

package org.ai.forms.redesneurais;

import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableModel;

import org.ai.bo.neural.rede.RedeNeural;
import org.ai.forms.FormMenuPrincipal;
import org.ai.forms.redesneurais.FrameRedeNeuralManutencao;
import org.ai.forms.utils.ColumnResizer;

/**
 *
 * @author  Edison
 */
public class FrameRedeNeuralConsulta extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    
    private List<RedeNeural> listRedes;
    private DefaultTableModel modelRedes;
    private FormMenuPrincipal formPrincipal;
    
    
    /** Creates new form FrameRedeNeuralConsulta
     * @param formPrincipal 
     */
    public FrameRedeNeuralConsulta(FormMenuPrincipal formPrincipal) {
        initComponents();
        this.formPrincipal = formPrincipal;
        updateTableRedes();
    }
    
     public void updateTableRedes() {
        updateListRedes();
        tableRedes.setModel(modelRedes);
        tableRedes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableRedes.setRowSelectionAllowed(true);
        tableRedes.setColumnSelectionAllowed(false);
        ColumnResizer.adjustColumnPreferredWidths(tableRedes);
        tableRedes.revalidate();
        lblTotalRedes.setText(Integer.toString(listRedes.size()));

    }

    private void updateListRedes() {
        listRedes = RedeNeural.findAll();
        String[] collumnNames = new String[]{"Nome", "Status"};
        String[][] data = new String[listRedes.size()][];
        for (int i = 0; i < listRedes.size(); i++) {
            data[i] = new String[]{
                        listRedes.get(i).getNome(),
                        listRedes.get(i).getStatus().getNome()
                    };
        }
        modelRedes = new DefaultTableModel(data, collumnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRedes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotalRedes = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Consulta de Redes Neurais");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Node.png"))); // NOI18N

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        tableRedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableRedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRedesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRedes);

        jLabel1.setText("Total de Redes:");

        lblTotalRedes.setText("total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalRedes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalRedes))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void tableRedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRedesMouseClicked
    RedeNeural rede = listRedes.get(tableRedes.getSelectedRow());
    FrameRedeNeuralManutencao frame = new FrameRedeNeuralManutencao(formPrincipal,rede);
    formPrincipal.getDesktopPane().add(frame);
    frame.setLocation((int) this.getBounds().getX() + this.getWidth(), (int) this.getBounds().getY());
    frame.setVisible(true);
    frame.addInternalFrameListener(new InternalFrameListener() {
            public void internalFrameOpened(InternalFrameEvent e) {}
            public void internalFrameClosing(InternalFrameEvent e) {}
            public void internalFrameClosed(InternalFrameEvent e) {
                updateTableRedes();
            }
            public void internalFrameIconified(InternalFrameEvent e) {}
            public void internalFrameDeiconified(InternalFrameEvent e) {}
            public void internalFrameActivated(InternalFrameEvent e) {}
            public void internalFrameDeactivated(InternalFrameEvent e) {}
        });
}//GEN-LAST:event_tableRedesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalRedes;
    private javax.swing.JTable tableRedes;
    // End of variables declaration//GEN-END:variables

}
