/*
 * FrameRedeNeuralGlobalClientes.java
 *
 * Created on October 13, 2008, 9:38 AM
 */
package org.ai.forms.redesneurais;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

import org.ai.agentes.AnalisadorPerfilCliente;
import org.ai.agentes.listeners.AnaliseListener;
import org.ai.bo.ambiente.Cliente;
import org.ai.bo.ambiente.Transacao;
import org.ai.bo.analise.Caso;
import org.ai.bo.analise.CasoCliente;
import org.ai.bo.analise.TipoCaso;
import org.ai.bo.neural.rede.RedeNeural;
import org.ai.bo.neural.rede.StatusRedeNeural;
import org.ai.forms.FormMenuPrincipal;
import org.ai.forms.ambiente.transacoes.FrameTransacaoSelecaoTreinamento;
import org.ai.forms.redesneurais.FrameRedeNeuralManutencao;

/**
 *
 * @author  Edison
 */
public class FrameRedeNeuralGlobalClientes extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private List<Cliente> clientes;
    private List<Transacao> transacoes;
    private RedeNeural redeGlobalClientes;
    private FormMenuPrincipal formPrincipal;

    /** Creates new form FrameRedeNeuralGlobalClientes
     * @param formPrincipal 
     */
    public FrameRedeNeuralGlobalClientes(FormMenuPrincipal formPrincipal) {
        initComponents();
        this.formPrincipal = formPrincipal;
        redeGlobalClientes = RedeNeural.find(1);
        if (redeGlobalClientes.getId() == 0 || redeGlobalClientes == null) {
            redeGlobalClientes = new RedeNeural();
            redeGlobalClientes.setId(1);
            redeGlobalClientes.setNome("Global: Clientes");
        }
        clientes = Cliente.findAll();
        lblTotalClientes.setText(Integer.toString(clientes.size()));
        lblTotalTransacoes.setText(Integer.toString(Transacao.count()));
        lblTotalClientesAnalisados.setText("0");
        updateLabelsCasos();
        updateLabelsRedeNeural();
    }

    private void updateLabelsCasos(){
        transacoes = Transacao.findAll();
        int totalTreinamento = 0;
        int totalTeste = 0;
        for (Transacao transacao : transacoes) {
            if(transacao.isFlagTeste()){
                totalTeste++;
            }
            if(transacao.isFlagTreinamento()){
                totalTreinamento++;
            }
        }
        lblTotalCasosTreinamento.setText(Integer.toString(totalTreinamento));
        lblTotalCasosTeste.setText(Integer.toString(totalTeste));
    }

    private void updateLabelsRedeNeural() {
        lblStatusRedeNeural.setText(redeGlobalClientes.getStatus().getNome());
        if (redeGlobalClientes.getStatus() == StatusRedeNeural.TREINADA) {
            lblDhUltimoTreinamentoRedeNeural.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss SSS").format(redeGlobalClientes.getDadosTreinamento().getDhUltimoTreinamento().getTime()));
        } else {
            lblDhUltimoTreinamentoRedeNeural.setText("Não possui treinamento");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioSelecaoTransacao = new javax.swing.ButtonGroup();
        btnFechar = new javax.swing.JButton();
        btnExibirRedeGlobalClientes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTotalClientes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalTransacoes = new javax.swing.JLabel();
        prgAnalisePerfilCliente = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        lblTotalClientesAnalisados = new javax.swing.JLabel();
        btnAnalisarClientes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblDhUltimoTreinamentoRedeNeural = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblStatusRedeNeural = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCarregarCasos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblTotalCasosTeste = new javax.swing.JLabel();
        lblTotalCasosTreinamento = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSelecionarCasos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Rede Neural Global");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/web_16.png"))); // NOI18N

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnExibirRedeGlobalClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Node.png"))); // NOI18N
        btnExibirRedeGlobalClientes.setText("Exibir Rede");
        btnExibirRedeGlobalClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirRedeGlobalClientesActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Análise"));

        lblTotalClientes.setText("total");

        jLabel1.setText("Total de Clientes:");

        jLabel2.setText("Total Transações:");

        lblTotalTransacoes.setText("total");

        prgAnalisePerfilCliente.setStringPainted(true);

        jLabel3.setText("Total Analisados:");

        lblTotalClientesAnalisados.setText("total");

        btnAnalisarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Bank User Rating.png"))); // NOI18N
        btnAnalisarClientes.setText("Analisar Clientes");
        btnAnalisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(prgAnalisePerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAnalisarClientes))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTotalClientes)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalClientesAnalisados))
                            .addComponent(lblTotalTransacoes))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalClientes)
                    .addComponent(jLabel3)
                    .addComponent(lblTotalClientesAnalisados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalTransacoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prgAnalisePerfilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalisarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Rede Neural"));

        lblDhUltimoTreinamentoRedeNeural.setText("ultimoTreinamento");

        jLabel9.setText("Ultimo Treinamento:");

        lblStatusRedeNeural.setText("statusRede");

        jLabel8.setText("Estado da Rede:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusRedeNeural)
                    .addComponent(lblDhUltimoTreinamentoRedeNeural))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusRedeNeural)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblDhUltimoTreinamentoRedeNeural))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Casos"));

        btnCarregarCasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/web_save_16.png"))); // NOI18N
        btnCarregarCasos.setText("Definir Casos RN");
        btnCarregarCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCasosActionPerformed(evt);
            }
        });

        jLabel4.setText("Casos Teste:");

        lblTotalCasosTeste.setText("total");

        lblTotalCasosTreinamento.setText("total");

        jLabel5.setText("Casos Treinamento:");

        btnSelecionarCasos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/web_edit_16.png"))); // NOI18N
        btnSelecionarCasos.setText("Selecionar Casos");
        btnSelecionarCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarCasosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalCasosTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalCasosTreinamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(btnCarregarCasos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionarCasos)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblTotalCasosTreinamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalCasosTeste)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSelecionarCasos)
                            .addComponent(btnCarregarCasos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExibirRedeGlobalClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnExibirRedeGlobalClientes))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void btnAnalisarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisarClientesActionPerformed
    final FrameRedeNeuralGlobalClientes frame = this;
    final AnalisadorPerfilCliente analisador = new AnalisadorPerfilCliente(Cliente.findAll());

    analisador.addAnaliseListener(new AnaliseListener() {

        public void analiseIniciada() {
            prgAnalisePerfilCliente.setValue(0);
            btnAnalisarClientes.setEnabled(false);
        }

        public void progressoAtualizado() {
            prgAnalisePerfilCliente.setValue(((analisador.getTotalClientesAnalisados()) / analisador.getTotalClientes()) * 100);
            lblTotalClientesAnalisados.setText(Integer.toString(analisador.getTotalClientesAnalisados()));
        }

        public void analiseFinalizada() {
            prgAnalisePerfilCliente.setValue(100);
            btnAnalisarClientes.setEnabled(true);


            SwingUtilities.invokeLater(new Runnable() {

                public void run() {
                    JOptionPane.showMessageDialog(frame, "Analise Finalizada");
                }
            });
        }
    });

    Thread threadAnalisador = new Thread(analisador);
    threadAnalisador.setName("Analisador");
    threadAnalisador.setPriority(Thread.MIN_PRIORITY);
    threadAnalisador.start();
}//GEN-LAST:event_btnAnalisarClientesActionPerformed

private void btnExibirRedeGlobalClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirRedeGlobalClientesActionPerformed
    FrameRedeNeuralManutencao frame = new FrameRedeNeuralManutencao(formPrincipal, redeGlobalClientes);
    formPrincipal.getDesktopPane().add(frame);
    frame.setLocation((int) this.getBounds().getX() + this.getWidth(), (int) this.getBounds().getY());
    frame.setVisible(true);
    frame.addInternalFrameListener(new InternalFrameListener() {

        public void internalFrameOpened(InternalFrameEvent e) {
        }

        public void internalFrameClosing(InternalFrameEvent e) {
        }

        public void internalFrameClosed(InternalFrameEvent e) {
            updateLabelsRedeNeural();
        }

        public void internalFrameIconified(InternalFrameEvent e) {
        }

        public void internalFrameDeiconified(InternalFrameEvent e) {
        }

        public void internalFrameActivated(InternalFrameEvent e) {
        }

        public void internalFrameDeactivated(InternalFrameEvent e) {
        }
    });
}//GEN-LAST:event_btnExibirRedeGlobalClientesActionPerformed

private void btnCarregarCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCasosActionPerformed
    List<Caso> casosTreinamento = new ArrayList<Caso>();
    List<Caso> casosTeste = new ArrayList<Caso>();
    for (Cliente cliente : clientes) {
        casosTreinamento.addAll(cliente.getAnalisePerfil().recuperarCasosTreinamento(cliente, TipoCaso.TREINAMENTO));
        casosTeste.addAll(cliente.getAnalisePerfil().recuperarCasosTreinamento(cliente, TipoCaso.TESTE));
    }
    redeGlobalClientes.getDadosTreinamento().setLabels(CasoCliente.getLabels());
    redeGlobalClientes.getDadosTreinamento().setListCasosTreinamento(casosTreinamento);
    redeGlobalClientes.getDadosTreinamento().setListCasosTeste(casosTeste);
    redeGlobalClientes.update();
    JOptionPane.showMessageDialog(this, "Casos carregados com sucesso");
}//GEN-LAST:event_btnCarregarCasosActionPerformed

private void btnSelecionarCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarCasosActionPerformed
    FrameTransacaoSelecaoTreinamento frame = new FrameTransacaoSelecaoTreinamento(formPrincipal);
    formPrincipal.getDesktopPane().add(frame);
    frame.setLocation((int) this.getBounds().getX() + this.getWidth(), (int) this.getBounds().getY());
    frame.setVisible(true);
    frame.addInternalFrameListener(new InternalFrameListener() {

        public void internalFrameOpened(InternalFrameEvent e) {
        }

        public void internalFrameClosing(InternalFrameEvent e) {
        }

        public void internalFrameClosed(InternalFrameEvent e) {
            updateLabelsCasos();
        }

        public void internalFrameIconified(InternalFrameEvent e) {
        }

        public void internalFrameDeiconified(InternalFrameEvent e) {
        }

        public void internalFrameActivated(InternalFrameEvent e) {
        }

        public void internalFrameDeactivated(InternalFrameEvent e) {
        }
    });

}//GEN-LAST:event_btnSelecionarCasosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisarClientes;
    private javax.swing.JButton btnCarregarCasos;
    private javax.swing.JButton btnExibirRedeGlobalClientes;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSelecionarCasos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblDhUltimoTreinamentoRedeNeural;
    private javax.swing.JLabel lblStatusRedeNeural;
    private javax.swing.JLabel lblTotalCasosTeste;
    private javax.swing.JLabel lblTotalCasosTreinamento;
    private javax.swing.JLabel lblTotalClientes;
    private javax.swing.JLabel lblTotalClientesAnalisados;
    private javax.swing.JLabel lblTotalTransacoes;
    private javax.swing.JProgressBar prgAnalisePerfilCliente;
    private javax.swing.ButtonGroup radioSelecaoTransacao;
    // End of variables declaration//GEN-END:variables
}

