/*
 * FrameTreinamentoGraficoAprendizagem.java
 *
 * Created on October 10, 2008, 10:37 AM
 */
package org.ai.forms.redesneurais.rn3d;

import java.awt.BorderLayout;
import java.text.DecimalFormat;
import javax.vecmath.Vector3d;

import org.ai.bo.neural.rede.Neuronio;
import org.ai.bo.neural.rede.RedeNeural;
import org.ai.forms.redesneurais.rn3d.LayeredNetTopology;
import org.ai.forms.redesneurais.rn3d.RedeNeural3D;
import org.ai.forms.redesneurais.rn3d.listeners.NeuronioSelecionadoListener;

/**
 *
 * @author  Edison
 */
public class FrameRedeNeuralArquitetura3D extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    
    RedeNeural rede;
    RedeNeural3D rn3d;
    float distance = -25.0F;
    DecimalFormat formatter = new DecimalFormat("0.0000000000");
    
    /** Creates new form FrameTreinamentoGraficoAprendizagem
     * @param rede 
     */
    public FrameRedeNeuralArquitetura3D(RedeNeural rede) {
        initComponents();
        this.rede = rede;
        rn3d = new RedeNeural3D();
        
        rn3d.resetTopology(new LayeredNetTopology(rede.getArquitetura()));
        rn3d.resetView(distance);
        rn3d.addNeuronioSelecionadoListener(new NeuronioSelecionadoListener() {
            public void neuronioSelecionado(int index) {
                updateNeuronioSelecionado(index);
            }
        });
        sldZoom.setValue((int)(distance + 100));
                
        BorderLayout layout = new BorderLayout();
        panel3D.setLayout(layout);
        panel3D.add(rn3d, BorderLayout.CENTER);
       
        lblArquitetura.setText(rede.getArquitetura().toString());
        lblCamadas.setText(Integer.toString(rede.getCountCamadas()));
        lblNeuronios.setText(Integer.toString(rede.getCountNeuronios()));
        lblSinapses.setText(Integer.toString(rede.getCountSinapses()));
        
        lblBias.setText(formatter.format(0.00F));
        lblSaida.setText(formatter.format(0.00F));
        lblIndiceNeuronio.setText(Integer.toString(0));
        lblSinapsesNeuronio.setText(Integer.toString(0));
        
    }
    
    public void updateNeuronioSelecionado(int index){
        Neuronio neuronio = rede.getNeuronioByIndex(index);
        lblIndiceNeuronio.setText(Integer.toString(index));
        if(neuronio.getBias() != null){
            lblBias.setText(formatter.format(neuronio.getBias().getPeso()));
        } else {
            lblBias.setText(formatter.format(0.00F));
        }
        lblSaida.setText(formatter.format(neuronio.getSaida()));
        lblSinapsesNeuronio.setText(Integer.toString(neuronio.getSinapses().size()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        panel3D = new javax.swing.JPanel();
        sldZoom = new javax.swing.JSlider();
        panelNeuronio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblIndiceNeuronio = new javax.swing.JLabel();
        lblSinapsesNeuronio = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        lblBias = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblCamadas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblNeuronios = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblSinapses = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblArquitetura = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Arquitetura da Rede Neural em 3D");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/3d_modeling_16.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 465));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        panel3D.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout panel3DLayout = new javax.swing.GroupLayout(panel3D);
        panel3D.setLayout(panel3DLayout);
        panel3DLayout.setHorizontalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        panel3DLayout.setVerticalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        sldZoom.setOrientation(javax.swing.JSlider.VERTICAL);
        sldZoom.setPaintLabels(true);
        sldZoom.setPaintTicks(true);
        sldZoom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sldZoomPropertyChange(evt);
            }
        });

        panelNeuronio.setBorder(javax.swing.BorderFactory.createTitledBorder("Neurônio"));

        jLabel2.setText("Indice:");

        jLabel3.setText("Bias:");

        jLabel4.setText("Saída:");

        jLabel9.setText("Sinapses:");

        lblIndiceNeuronio.setText("numero");

        lblSinapsesNeuronio.setText("sinapses");

        lblSaida.setText("saida");

        lblBias.setText("bias");

        javax.swing.GroupLayout panelNeuronioLayout = new javax.swing.GroupLayout(panelNeuronio);
        panelNeuronio.setLayout(panelNeuronioLayout);
        panelNeuronioLayout.setHorizontalGroup(
            panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNeuronioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelNeuronioLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addComponent(jLabel9))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBias)
                    .addComponent(lblIndiceNeuronio)
                    .addComponent(lblSaida)
                    .addComponent(lblSinapsesNeuronio))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelNeuronioLayout.setVerticalGroup(
            panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNeuronioLayout.createSequentialGroup()
                .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIndiceNeuronio))
                    .addGroup(panelNeuronioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblBias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblSaida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelNeuronioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblSinapsesNeuronio))))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rede"));

        jLabel11.setText("Camadas:");

        lblCamadas.setText("camadas");

        jLabel13.setText("Neurônios:");

        lblNeuronios.setText("neuronios");

        jLabel15.setText("Sinapses:");

        lblSinapses.setText("sinapses");

        jLabel17.setText("Arquitetura:");

        lblArquitetura.setText("arquitetura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCamadas)
                    .addComponent(lblNeuronios)
                    .addComponent(lblSinapses)
                    .addComponent(lblArquitetura)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblArquitetura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblCamadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNeuronios)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSinapses)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(sldZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(110, 110, 110))
                        .addComponent(btnFechar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNeuronio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel3D, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sldZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNeuronio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void sldZoomPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sldZoomPropertyChange
    distance = (sldZoom.getValue()-100);
    Vector3d posicao = rn3d.getPosicao3D();
    posicao.setZ(distance);
    rn3d.setPosicao3D(posicao);
}//GEN-LAST:event_sldZoomPropertyChange

private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
    rn3d.stopRenderer();
}//GEN-LAST:event_formInternalFrameClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArquitetura;
    private javax.swing.JLabel lblBias;
    private javax.swing.JLabel lblCamadas;
    private javax.swing.JLabel lblIndiceNeuronio;
    private javax.swing.JLabel lblNeuronios;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblSinapses;
    private javax.swing.JLabel lblSinapsesNeuronio;
    private javax.swing.JPanel panel3D;
    private javax.swing.JPanel panelNeuronio;
    private javax.swing.JSlider sldZoom;
    // End of variables declaration//GEN-END:variables
}
