/*
 * FrameCartaoConsulta.java
 *
 * Created on September 30, 2008, 11:30 AM
 */
package org.ai.forms.ambiente.cartoes;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableModel;

import org.ai.bo.ambiente.Cartao;
import org.ai.forms.FormMenuPrincipal;
import org.ai.forms.utils.ColumnResizer;

/**
 *
 * @author  Edison
 */
public class FrameCartaoConsulta extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private List<Cartao> listCartoes;
    private DefaultTableModel modelCartoes;
    Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
    FormMenuPrincipal formPrincipal;

    /** Creates new form FrameCartaoConsulta
     * @param formPrincipal 
     */
    public FrameCartaoConsulta(FormMenuPrincipal formPrincipal) {
        initComponents();
        this.formPrincipal = formPrincipal;
        updateTableCartoes();
    }

    public void updateTableCartoes() {
        updateListCartoes();
        tableCartoes.setModel(modelCartoes);
        tableCartoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableCartoes.setRowSelectionAllowed(true);
        tableCartoes.setColumnSelectionAllowed(false);
        ColumnResizer.adjustColumnPreferredWidths(tableCartoes);
        tableCartoes.revalidate();
        lblTotalCartoes.setText(Integer.toString(listCartoes.size()));

    }

    private void updateListCartoes() {
        listCartoes = Cartao.findAll();
        String[] collumnNames = new String[]{"Bandeira", "Numero", "Cliente", "Limite"};
        String[][] data = new String[listCartoes.size()][];
        for (int i = 0; i < listCartoes.size(); i++) {
            data[i] = new String[]{
                        listCartoes.get(i).getBandeira().getNome(),
                        listCartoes.get(i).getNumCartao(),
                        listCartoes.get(i).getCliente().getNome(),
                        new DecimalFormat("R$ #,###,##0.00").format(listCartoes.get(i).getLimite())
                    };
        }
        modelCartoes = new DefaultTableModel(data, collumnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCartoes = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalCartoes = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consulta de Cartão");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Credit Card.png"))); // NOI18N

        tableCartoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCartoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCartoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCartoes);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de Cartões: ");

        lblTotalCartoes.setText("total");

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Credit Card Add.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalCartoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalCartoes)
                    .addComponent(btnCadastrar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    FrameCartaoCadastro frame = new FrameCartaoCadastro();
    formPrincipal.getDesktopPane().add(frame);
    frame.setLocation((int) this.getBounds().getX() - frame.getWidth(), (int) this.getBounds().getY());
    frame.setVisible(true);
    frame.addInternalFrameListener(new InternalFrameListener() {
            public void internalFrameOpened(InternalFrameEvent e) {}
            public void internalFrameClosing(InternalFrameEvent e) {}
            public void internalFrameClosed(InternalFrameEvent e) {
                updateTableCartoes();
            }
            public void internalFrameIconified(InternalFrameEvent e) {}
            public void internalFrameDeiconified(InternalFrameEvent e) {}
            public void internalFrameActivated(InternalFrameEvent e) {}
            public void internalFrameDeactivated(InternalFrameEvent e) {}
        });
}//GEN-LAST:event_btnCadastrarActionPerformed

private void tableCartoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCartoesMouseClicked
    Cartao cartao = listCartoes.get(tableCartoes.getSelectedRow());
    FrameCartaoManutencao frame = new FrameCartaoManutencao(formPrincipal,cartao);
    formPrincipal.getDesktopPane().add(frame);
    frame.setLocation((int) this.getBounds().getX() + this.getWidth(), (int) this.getBounds().getY());
    frame.setVisible(true);
    frame.addInternalFrameListener(new InternalFrameListener() {
            public void internalFrameOpened(InternalFrameEvent e) {}
            public void internalFrameClosing(InternalFrameEvent e) {}
            public void internalFrameClosed(InternalFrameEvent e) {
                updateTableCartoes();
            }
            public void internalFrameIconified(InternalFrameEvent e) {}
            public void internalFrameDeiconified(InternalFrameEvent e) {}
            public void internalFrameActivated(InternalFrameEvent e) {}
            public void internalFrameDeactivated(InternalFrameEvent e) {}
        });
}//GEN-LAST:event_tableCartoesMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalCartoes;
    private javax.swing.JTable tableCartoes;
    // End of variables declaration//GEN-END:variables
}
