/*
 * FrameCartaoCadastro.java
 *
 * Created on September 30, 2008, 11:44 AM
 */
package org.ai.forms.ambiente.cartoes;

import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import org.ai.bo.ambiente.Banco;
import org.ai.bo.ambiente.Bandeira;
import org.ai.bo.ambiente.Cartao;
import org.ai.bo.ambiente.Cliente;

/**
 *
 * @author  Edison
 */
public class FrameCartaoCadastro extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    
    private List<Banco> listBancos;
    private List<Cliente> listClientes;
    private List<Bandeira> listBandeiras;
    private Banco banco;
    private Cliente cliente;
    private Bandeira bandeira;
    private DefaultComboBoxModel modelBancos;
    private DefaultComboBoxModel modelBandeiras;


    public FrameCartaoCadastro() {
        initComponents();
        updateComboClientes();
        updateComboBancos();
        updateComboBandeiras();
    }
    
    public FrameCartaoCadastro(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        
        //Define o cliente fixo no combo
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(new String[]{cliente.getNome()});
        cmbCliente.setModel(comboModel);
        cmbCliente.revalidate();
        cmbCliente.setEnabled(false);
        
        updateComboBancos();
        updateComboBandeiras();
    }
    

    private void updateComboClientes() {
        listClientes = Cliente.findAll();
        String[] data = new String[listClientes.size() + 1];
        data[0] = "Selecione um Cliente...";
        for (int i = 0; i < listClientes.size(); i++) {
            data[i + 1] = listClientes.get(i).getNome();
        }
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(data);
        cmbCliente.setModel(comboModel);
        cmbCliente.revalidate();
        cliente = null;
    }

    private void updateListBancos() {
        listBancos = Banco.findAll();
        String[] data = new String[listBancos.size() + 1];
        data[0] = "Selecione um Banco...";
        for (int i = 0; i < listBancos.size(); i++) {
            data[i + 1] = listBancos.get(i).getNome();
        }
        modelBancos = new DefaultComboBoxModel(data);
    }

    private void updateComboBancos() {
        updateListBancos();
        cmbBanco.setModel(modelBancos);
        cmbBanco.revalidate();
        banco = null;
    }

    private void updateListBandeiras() {
        listBandeiras = Bandeira.findAll();
        String[] data = new String[listBandeiras.size() + 1];
        data[0] = "Selecione uma Bandeira...";
        for (int i = 0; i < listBandeiras.size(); i++) {
            data[i + 1] = listBandeiras.get(i).getNome();
        }
        modelBandeiras = new DefaultComboBoxModel(data);
    }

    private void updateComboBandeiras() {
        updateListBandeiras();
        cmbBandeira.setModel(modelBandeiras);
        cmbBandeira.revalidate();
        bandeira = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroCartao = new javax.swing.JTextField();
        txtCodSeguranca = new javax.swing.JTextField();
        cmbCliente = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbBanco = new javax.swing.JComboBox();
        cmbBandeira = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAtivacao = new javax.swing.JFormattedTextField();
        txtExpiracao = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chkBloqueado = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Cartão");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Credit Card.png"))); // NOI18N

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Credit Card Add.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero");

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        jLabel3.setText("Banco");

        cmbBanco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBancoActionPerformed(evt);
            }
        });

        cmbBandeira.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBandeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBandeiraActionPerformed(evt);
            }
        });

        jLabel4.setText("Bandeira");

        jLabel6.setText("Ativação");

        jLabel7.setText("Expiração");

        jLabel5.setText("Limite");

        jLabel8.setText("Bloqueado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBanco, 0, 246, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(txtCodSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCliente, 0, 246, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBandeira, 0, 246, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(106, 106, 106)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtLimite, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtAtivacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCadastrar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtExpiracao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkBloqueado)
                                    .addComponent(btnFechar))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpiracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtAtivacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8))
                    .addComponent(chkBloqueado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnCadastrar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    if (cliente == null) {
        JOptionPane.showMessageDialog(this, "Selecione um Cliente");
    } else if (banco == null) {
        JOptionPane.showMessageDialog(this, "Selecione um Banco");
    } else if (bandeira == null) {
        JOptionPane.showMessageDialog(this, "Selecione uma Bandeira");
    } else {
        int resposta = JOptionPane.showConfirmDialog(this, "Confirma cadastro do cartão " + txtNumeroCartao.getText() + "?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            Cartao cartao = new Cartao();
            cartao.setNumCartao(txtNumeroCartao.getText());
            cartao.setCliente(cliente);
            cartao.setBanco(banco);
            cartao.setBandeira(bandeira);
            cartao.setBloqueado(chkBloqueado.isSelected());
            cartao.setCodSeguranca(Integer.parseInt(txtCodSeguranca.getText()));
            Calendar ativacao = Calendar.getInstance();
            Calendar expiracao = Calendar.getInstance();
            try {
                ativacao.setTime(new SimpleDateFormat("dd/MM/yyyy").parse(txtAtivacao.getText()));
                expiracao.setTime(new SimpleDateFormat("dd/MM/yyyy").parse(txtExpiracao.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(FrameCartaoCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            cartao.setDataAtivacao(ativacao);
            cartao.setDataExpiracao(expiracao);
            try {
                cartao.setLimite(new DecimalFormat("#,###,###.00").parse(txtLimite.getText()).doubleValue());
            } catch (ParseException ex) {
                Logger.getLogger(FrameCartaoManutencao.class.getName()).log(Level.SEVERE, null, ex);
            }
            boolean created = cartao.create();
            if (created) {
                cartao.getCliente().getCartoes().add(cartao);
                JOptionPane.showMessageDialog(this, "Cartão " + cartao.getNumCartao() + " cadastrado com sucesso");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o cartão " + cartao.getNumCartao());
            }
            dispose();
        }
    }
}//GEN-LAST:event_btnCadastrarActionPerformed

private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
if (cmbCliente.getSelectedIndex() != 0) {
        cliente = listClientes.get(cmbCliente.getSelectedIndex() - 1);
    } else {
        cliente = null;
    }
}//GEN-LAST:event_cmbClienteActionPerformed

private void cmbBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBancoActionPerformed
if (cmbBanco.getSelectedIndex() != 0) {
        banco = listBancos.get(cmbBanco.getSelectedIndex() - 1);
    } else {
        banco = null;
    }
}//GEN-LAST:event_cmbBancoActionPerformed

private void cmbBandeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBandeiraActionPerformed
if (cmbBandeira.getSelectedIndex() != 0) {
        bandeira = listBandeiras.get(cmbBandeira.getSelectedIndex() - 1);
    } else {
        bandeira = null;
    }
}//GEN-LAST:event_cmbBandeiraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JCheckBox chkBloqueado;
    private javax.swing.JComboBox cmbBanco;
    private javax.swing.JComboBox cmbBandeira;
    private javax.swing.JComboBox cmbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField txtAtivacao;
    private javax.swing.JTextField txtCodSeguranca;
    private javax.swing.JFormattedTextField txtExpiracao;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtNumeroCartao;
    // End of variables declaration//GEN-END:variables
}
