/*
 * FrameTransacaoConsulta.java
 *
 * Created on October 4, 2008, 2:11 PM
 */
package org.ai.forms.ambiente.transacoes;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableModel;

import org.ai.agentes.AnalisadorTransacao;
import org.ai.agentes.listeners.AnaliseListener;
import org.ai.bo.ambiente.Transacao;
import org.ai.forms.FormMenuPrincipal;
import org.ai.forms.utils.ColumnResizer;
import org.jvnet.substance.api.renderers.SubstanceDefaultTableCellRenderer.BooleanRenderer;

/**
 *
 * @author  Edison
 */
public class FrameTransacaoConsulta extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private List<Transacao> listTransacoes;
    private DefaultTableModel modelTransacoes;
    Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
    FormMenuPrincipal formPrincipal;

    /** Creates new form FrameTransacaoConsulta
     * @param formPrincipal 
     */
    public FrameTransacaoConsulta(FormMenuPrincipal formPrincipal) {
        initComponents();
        this.formPrincipal = formPrincipal;
        updateTableTransacoes();
    }

    private void updateTableTransacoes() {
        listTransacoes = Transacao.findAll();
        String[] collumnNames = new String[]{"Cartão", "Terminal", "Cidade", "Status", "Pts", "Trn", "Tst"};
        Object[][] data = new Object[listTransacoes.size()][];
        for (int i = 0; i < listTransacoes.size(); i++) {
            data[i] = new Object[]{
                        listTransacoes.get(i).getCartao().getNumCartao(),
                        listTransacoes.get(i).getTerminalPOS().getEstabelecimento().getNome(),
                        listTransacoes.get(i).getTerminalPOS().getEstabelecimento().getCidade().getNome(),
                        listTransacoes.get(i).getStatus().getNome(),
                        listTransacoes.get(i).getPontuacao(),
                        listTransacoes.get(i).isFlagTreinamento(),
                        listTransacoes.get(i).isFlagTeste()
                    };
        }
        modelTransacoes = new DefaultTableModel(data, collumnNames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public void setValueAt(Object aValue, int row, int column) {
                super.setValueAt(aValue, row, column);
                if (column == getColumnCount() - 2) { //Treinamento
                    listTransacoes.get(row).setFlagTreinamento((Boolean) aValue);
                    listTransacoes.get(row).update();
                }
                if (column == getColumnCount() - 1) { //Treinamento
                    listTransacoes.get(row).setFlagTeste((Boolean) aValue);
                    listTransacoes.get(row).update();
                }
            }
        };
        tableTransacoes.setModel(modelTransacoes);
        tableTransacoes.getColumnModel().getColumn(collumnNames.length - 2).setCellEditor(new DefaultCellEditor(new JCheckBox()));
        tableTransacoes.getColumnModel().getColumn(collumnNames.length - 2).setCellRenderer(new BooleanRenderer());
        tableTransacoes.getColumnModel().getColumn(collumnNames.length - 1).setCellEditor(new DefaultCellEditor(new JCheckBox()));
        tableTransacoes.getColumnModel().getColumn(collumnNames.length - 1).setCellRenderer(new BooleanRenderer());

        tableTransacoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableTransacoes.setRowSelectionAllowed(true);
        tableTransacoes.setColumnSelectionAllowed(false);
        ColumnResizer.adjustColumnPreferredWidths(tableTransacoes);
        tableTransacoes.revalidate();
        lblTotalTransacoes.setText(Integer.toString(listTransacoes.size()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTransacoes = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTotalTransacoes = new javax.swing.JLabel();
        btnAnalisarTodas = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consulta de Transações");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/transaction_bank_16.png"))); // NOI18N

        tableTransacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransacoesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTransacoes);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/transaction_bank_add_16.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Transações:");

        lblTotalTransacoes.setText("total");

        btnAnalisarTodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/transaction_bank_zoom_16.png"))); // NOI18N
        btnAnalisarTodas.setText("Analisar Todas");
        btnAnalisarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisarTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalTransacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnAnalisarTodas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnCadastrar)
                    .addComponent(jLabel3)
                    .addComponent(lblTotalTransacoes)
                    .addComponent(btnAnalisarTodas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    FrameTransacaoManutencao frame = new FrameTransacaoManutencao();
    formPrincipal.getDesktopPane().add(frame);
    frame.setLocation((int) this.getBounds().getX() - frame.getWidth(), (int) this.getBounds().getY());
    frame.setVisible(true);
    frame.addInternalFrameListener(new InternalFrameListener() {

        public void internalFrameOpened(InternalFrameEvent e) {
        }

        public void internalFrameClosing(InternalFrameEvent e) {
        }

        public void internalFrameClosed(InternalFrameEvent e) {
            updateTableTransacoes();
        }

        public void internalFrameIconified(InternalFrameEvent e) {
        }

        public void internalFrameDeiconified(InternalFrameEvent e) {
        }

        public void internalFrameActivated(InternalFrameEvent e) {
        }

        public void internalFrameDeactivated(InternalFrameEvent e) {
        }
    });
}//GEN-LAST:event_btnCadastrarActionPerformed

private void tableTransacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransacoesMouseClicked
    if (tableTransacoes.getSelectedRow() >= 0) {
        Transacao transacao = listTransacoes.get(tableTransacoes.getSelectedRow());
        FrameTransacaoManutencao frame = new FrameTransacaoManutencao(transacao);
        formPrincipal.getDesktopPane().add(frame);
        frame.setLocation((int) this.getBounds().getX() + this.getWidth(), (int) this.getBounds().getY());
        frame.setVisible(true);
        frame.addInternalFrameListener(new InternalFrameListener() {

            public void internalFrameOpened(InternalFrameEvent e) {
            }

            public void internalFrameClosing(InternalFrameEvent e) {
            }

            public void internalFrameClosed(InternalFrameEvent e) {
                updateTableTransacoes();
            }

            public void internalFrameIconified(InternalFrameEvent e) {
            }

            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            public void internalFrameActivated(InternalFrameEvent e) {
            }

            public void internalFrameDeactivated(InternalFrameEvent e) {
            }
        });
    }
}//GEN-LAST:event_tableTransacoesMouseClicked

private void btnAnalisarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisarTodasActionPerformed
    final FrameTransacaoConsulta frame = this;
    final AnalisadorTransacao analisador = new AnalisadorTransacao(listTransacoes);
    analisador.addAnaliseListener(new AnaliseListener() {

        public void analiseIniciada() {
            lblTotalTransacoes.setText("0/" + listTransacoes.size());
            btnAnalisarTodas.setEnabled(false);
        }

        public void progressoAtualizado() {
            lblTotalTransacoes.setText(analisador.getTotalTransacoesAnalisadas() + "/" + listTransacoes.size());
        }

        public void analiseFinalizada() {
            btnAnalisarTodas.setEnabled(true);
            lblTotalTransacoes.setText(Integer.toString(listTransacoes.size()));
            

            SwingUtilities.invokeLater(new Runnable() {

                public void run() {
                    updateTableTransacoes();
                    JOptionPane.showMessageDialog(frame, "Analise Finalizada");
                }
            });
        }
    });

    Thread threadAnalisador = new Thread(analisador);
    threadAnalisador.setName("Analisador");
    threadAnalisador.setPriority(Thread.MIN_PRIORITY);
    threadAnalisador.start();
}//GEN-LAST:event_btnAnalisarTodasActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisarTodas;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTotalTransacoes;
    private javax.swing.JTable tableTransacoes;
    // End of variables declaration//GEN-END:variables
}
