/*
 * FormMenu.java
 *
 * Created on 16/09/2008, 20:55:07
 */
package org.ai.forms;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;

import org.ai.dao.factory.Db4oDAOFactory;
import org.ai.forms.ambiente.analistas.FrameAnalistaConsulta;
import org.ai.forms.ambiente.bancos.FrameBancoConsulta;
import org.ai.forms.ambiente.cartoes.FrameCartaoConsulta;
import org.ai.forms.ambiente.cidades.FrameCidadeConsulta;
import org.ai.forms.ambiente.clientes.FrameClienteConsulta;
import org.ai.forms.ambiente.estabelecimentos.FrameEstabelecimentoConsulta;
import org.ai.forms.ambiente.estados.FrameEstadoConsulta;
import org.ai.forms.ambiente.ramos.FrameRamoAtividadeConsulta;
import org.ai.forms.ambiente.regioes.FrameRegiaoConsulta;
import org.ai.forms.ambiente.terminais.FrameTerminalConsulta;
import org.ai.forms.ambiente.transacoes.FrameTransacaoConsulta;
import org.ai.forms.redesneurais.FrameRedeNeuralConsulta;
import org.ai.forms.redesneurais.FrameRedeNeuralGlobalClientes;

/**
 *
 * @author Edison
 */
public class FormMenuPrincipal extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    /** Creates new form FormMenu */
    public FormMenuPrincipal() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/edu/facear/tcc/forms/resources/Physics.png")));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        redeNeuralMenu = new javax.swing.JMenu();
        redeGlobalMenuItem = new javax.swing.JMenuItem();
        todasRedesMenuItem = new javax.swing.JMenuItem();
        ambienteMenu = new javax.swing.JMenu();
        analistasMenuItem = new javax.swing.JMenuItem();
        bancosMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        regioesMenuItem = new javax.swing.JMenuItem();
        estadosMenuItem = new javax.swing.JMenuItem();
        cidadesMenuItem = new javax.swing.JMenuItem();
        clientesMenuItem = new javax.swing.JMenuItem();
        ramosAtividadeMenuItem = new javax.swing.JMenuItem();
        estabelecimentosMenuItem = new javax.swing.JMenuItem();
        cartoesMenuItem = new javax.swing.JMenuItem();
        terminaisMenuItem = new javax.swing.JMenuItem();
        transacoesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gerenciador de Detecção de Fraudes em Transação de Cartão de Crédito");
        setName("frameMenu"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        redeNeuralMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Node.png"))); // NOI18N
        redeNeuralMenu.setText("Rede Neural");

        redeGlobalMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/web_16.png"))); // NOI18N
        redeGlobalMenuItem.setText("Global");
        redeGlobalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redeGlobalMenuItemActionPerformed(evt);
            }
        });
        redeNeuralMenu.add(redeGlobalMenuItem);

        todasRedesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Node.png"))); // NOI18N
        todasRedesMenuItem.setText("Todas Redes");
        todasRedesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasRedesMenuItemActionPerformed(evt);
            }
        });
        redeNeuralMenu.add(todasRedesMenuItem);

        menuBar.add(redeNeuralMenu);

        ambienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/web_16.png"))); // NOI18N
        ambienteMenu.setText("Ambiente");

        analistasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Accountant.png"))); // NOI18N
        analistasMenuItem.setText("Analistas");
        analistasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analistasMenuItemActionPerformed(evt);
            }
        });
        ambienteMenu.add(analistasMenuItem);

        bancosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/bank_16.png"))); // NOI18N
        bancosMenuItem.setText("Bancos");
        bancosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bancosMenuItemActionPerformed(evt);
            }
        });
        ambienteMenu.add(bancosMenuItem);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/location_16.png"))); // NOI18N
        jMenu1.setText("Localidades");

        regioesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/location_16.png"))); // NOI18N
        regioesMenuItem.setText("Regiões");
        regioesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regioesMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(regioesMenuItem);

        estadosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/location_16.png"))); // NOI18N
        estadosMenuItem.setText("Estados");
        estadosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadosMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(estadosMenuItem);

        cidadesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/location_16.png"))); // NOI18N
        cidadesMenuItem.setText("Cidades");
        cidadesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadesMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cidadesMenuItem);

        ambienteMenu.add(jMenu1);

        clientesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Bank User.png"))); // NOI18N
        clientesMenuItem.setText("Clientes");
        clientesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesMenuItemActionPerformed(evt);
            }
        });
        ambienteMenu.add(clientesMenuItem);

        ramosAtividadeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/activity_16.png"))); // NOI18N
        ramosAtividadeMenuItem.setText("Ramos Atividade");
        ramosAtividadeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramosAtividadeMenuItemActionPerformed(evt);
            }
        });
        ambienteMenu.add(ramosAtividadeMenuItem);

        estabelecimentosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/industry_16.png"))); // NOI18N
        estabelecimentosMenuItem.setText("Estabelecimentos");
        estabelecimentosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estabelecimentosMenuItemActionPerformed(evt);
            }
        });
        ambienteMenu.add(estabelecimentosMenuItem);

        cartoesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Credit Card.png"))); // NOI18N
        cartoesMenuItem.setText("Cartões");
        cartoesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartoesMenuItemActionPerformed(evt);
            }
        });
        ambienteMenu.add(cartoesMenuItem);

        terminaisMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Card Swiper.png"))); // NOI18N
        terminaisMenuItem.setText("Terminais");
        terminaisMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminaisMenuItemActionPerformed(evt);
            }
        });
        ambienteMenu.add(terminaisMenuItem);

        transacoesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/transaction_bank_16.png"))); // NOI18N
        transacoesMenuItem.setText("Transações");
        transacoesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transacoesMenuItemActionPerformed(evt);
            }
        });
        ambienteMenu.add(transacoesMenuItem);

        menuBar.add(ambienteMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void analistasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analistasMenuItemActionPerformed
        FrameAnalistaConsulta form = new FrameAnalistaConsulta(this);
        desktopPane.add(form);
        form.setLocation(((tela.width) - (form.getSize().width)) / 2, ((tela.height) - (form.getSize().height)) / 3);
        form.setVisible(true);
    }//GEN-LAST:event_analistasMenuItemActionPerformed

    private void bancosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bancosMenuItemActionPerformed
        FrameBancoConsulta form = new FrameBancoConsulta(this);
        desktopPane.add(form);
        form.setLocation(((tela.width) - (form.getSize().width)) / 2, ((tela.height) - (form.getSize().height)) / 3);
        form.setVisible(true);
    }//GEN-LAST:event_bancosMenuItemActionPerformed

    private void regioesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regioesMenuItemActionPerformed
        FrameRegiaoConsulta form = new FrameRegiaoConsulta(this);
        desktopPane.add(form);
        form.setLocation(((tela.width) - (form.getSize().width)) / 2, ((tela.height) - (form.getSize().height)) / 3);
        form.setVisible(true);
    }//GEN-LAST:event_regioesMenuItemActionPerformed

    private void cidadesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadesMenuItemActionPerformed
        FrameCidadeConsulta form = new FrameCidadeConsulta(this);
        desktopPane.add(form);
        form.setLocation(((tela.width) - (form.getSize().width)) / 2, ((tela.height) - (form.getSize().height)) / 3);
        form.setVisible(true);
    }//GEN-LAST:event_cidadesMenuItemActionPerformed

    private void clientesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesMenuItemActionPerformed
        FrameClienteConsulta form = new FrameClienteConsulta(this);
        desktopPane.add(form);
        form.setLocation(((tela.width) - (form.getSize().width)) / 2, ((tela.height) - (form.getSize().height)) / 3);
        form.setVisible(true);
    }//GEN-LAST:event_clientesMenuItemActionPerformed

private void ramosAtividadeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramosAtividadeMenuItemActionPerformed
    FrameRamoAtividadeConsulta form = new FrameRamoAtividadeConsulta(this);
    desktopPane.add(form);
    form.setLocation(((tela.width) - (form.getSize().width)) / 2, ((tela.height) - (form.getSize().height)) / 3);
    form.setVisible(true);
}//GEN-LAST:event_ramosAtividadeMenuItemActionPerformed

private void estabelecimentosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estabelecimentosMenuItemActionPerformed
    FrameEstabelecimentoConsulta form = new FrameEstabelecimentoConsulta(this);
    desktopPane.add(form);
    form.setLocation(((tela.width) - (form.getSize().width)) / 2, ((tela.height) - (form.getSize().height)) / 3);
    form.setVisible(true);
}//GEN-LAST:event_estabelecimentosMenuItemActionPerformed

private void cartoesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartoesMenuItemActionPerformed
    FrameCartaoConsulta frame = new FrameCartaoConsulta(this);
    desktopPane.add(frame);
    frame.setLocation(((tela.width) - (frame.getSize().width)) / 2, ((tela.height) - (frame.getSize().height)) / 3);
    frame.setVisible(true);
}//GEN-LAST:event_cartoesMenuItemActionPerformed

private void terminaisMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminaisMenuItemActionPerformed
    FrameTerminalConsulta frame = new FrameTerminalConsulta(this);
    desktopPane.add(frame);
    frame.setLocation(((tela.width) - (frame.getSize().width)) / 2, ((tela.height) - (frame.getSize().height)) / 3);
    frame.setVisible(true);
}//GEN-LAST:event_terminaisMenuItemActionPerformed

private void transacoesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transacoesMenuItemActionPerformed
    FrameTransacaoConsulta frame = new FrameTransacaoConsulta(this);
    desktopPane.add(frame);
    frame.setLocation(((tela.width) - (frame.getSize().width)) / 2, ((tela.height) - (frame.getSize().height)) / 3);
    frame.setVisible(true);
}//GEN-LAST:event_transacoesMenuItemActionPerformed

private void estadosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadosMenuItemActionPerformed
    FrameEstadoConsulta frame = new FrameEstadoConsulta(this);
    desktopPane.add(frame);
    frame.setLocation(((tela.width) - (frame.getSize().width)) / 2, ((tela.height) - (frame.getSize().height)) / 3);
    frame.setVisible(true);
}//GEN-LAST:event_estadosMenuItemActionPerformed

private void redeGlobalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redeGlobalMenuItemActionPerformed
    FrameRedeNeuralGlobalClientes frame = new FrameRedeNeuralGlobalClientes(this);
    desktopPane.add(frame);
    frame.setLocation(((tela.width) - (frame.getSize().width)) / 2, ((tela.height) - (frame.getSize().height)) / 3);
    frame.setVisible(true);
}//GEN-LAST:event_redeGlobalMenuItemActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    Db4oDAOFactory.closeConnection();
}//GEN-LAST:event_formWindowClosing

private void todasRedesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasRedesMenuItemActionPerformed
    FrameRedeNeuralConsulta frame = new FrameRedeNeuralConsulta(this);
    desktopPane.add(frame);
    frame.setLocation(((tela.width) - (frame.getSize().width)) / 2, ((tela.height) - (frame.getSize().height)) / 3);
    frame.setVisible(true);
}//GEN-LAST:event_todasRedesMenuItemActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ambienteMenu;
    private javax.swing.JMenuItem analistasMenuItem;
    private javax.swing.JMenuItem bancosMenuItem;
    private javax.swing.JMenuItem cartoesMenuItem;
    private javax.swing.JMenuItem cidadesMenuItem;
    private javax.swing.JMenuItem clientesMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem estabelecimentosMenuItem;
    private javax.swing.JMenuItem estadosMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem ramosAtividadeMenuItem;
    private javax.swing.JMenuItem redeGlobalMenuItem;
    private javax.swing.JMenu redeNeuralMenu;
    private javax.swing.JMenuItem regioesMenuItem;
    private javax.swing.JMenuItem terminaisMenuItem;
    private javax.swing.JMenuItem todasRedesMenuItem;
    private javax.swing.JMenuItem transacoesMenuItem;
    // End of variables declaration//GEN-END:variables


}
