/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameBancoConsulta.java
 *
 * Created on Sep 28, 2008, 6:10:13 PM
 */
package org.ai.forms.ambiente.bancos;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableModel;

import org.ai.bo.ambiente.Banco;
import org.ai.forms.FormMenuPrincipal;
import org.ai.forms.utils.ColumnResizer;

/**
 *
 * @author Edison
 */
public class FrameBancoConsulta extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    
    private List<Banco> listBancos;
    private DefaultTableModel modelBancos;
    Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
    FormMenuPrincipal formPrincipal;

    /** Creates new form FrameBancoConsulta
     * @param formPrincipal 
     */
    public FrameBancoConsulta(FormMenuPrincipal formPrincipal) {
        initComponents();
        this.formPrincipal = formPrincipal;
        updateTableBancos();
    }

    public void updateTableBancos() {
        updateListBancos();
        tableBancos.setModel(modelBancos);
        tableBancos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableBancos.setRowSelectionAllowed(true);
        tableBancos.setColumnSelectionAllowed(false);
        ColumnResizer.adjustColumnPreferredWidths(tableBancos);
        tableBancos.revalidate();
        lblTotalBancos.setText(Integer.toString(listBancos.size()));

    }

    private void updateListBancos() {
        listBancos = Banco.findAll();
        String[] collumnNames = new String[]{"Código", "Nome"};
        String[][] data = new String[listBancos.size()][];
        for (int i = 0; i < listBancos.size(); i++) {
            data[i] = new String[]{
                        Integer.toString(listBancos.get(i).getCodBanco()),
                        listBancos.get(i).getNome()
                    };
        }
        modelBancos = new DefaultTableModel(data, collumnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBancos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotalBancos = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consulta de Bancos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/bank_16.png"))); // NOI18N

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/bank_add_16.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        tableBancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ));
        tableBancos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBancosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBancos);

        jLabel1.setText("Total de Bancos: ");

        lblTotalBancos.setText("total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalBancos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalBancos)
                    .addComponent(btnFechar)
                    .addComponent(btnCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
}//GEN-LAST:event_btnFecharActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        FrameBancoCadastro form = new FrameBancoCadastro(this);
        formPrincipal.getDesktopPane().add(form);
        form.setLocation((int) this.getBounds().getX() - form.getWidth(), (int) this.getBounds().getY());
        form.setVisible(true);
}//GEN-LAST:event_btnCadastrarActionPerformed

    private void tableBancosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBancosMouseClicked
        Banco banco = listBancos.get(tableBancos.getSelectedRow());
        FrameBancoManutencao frame = new FrameBancoManutencao(this, banco);
        formPrincipal.getDesktopPane().add(frame);
        frame.setLocation((int) this.getBounds().getX() + this.getWidth(), (int) this.getBounds().getY());
        frame.setVisible(true);
        frame.addInternalFrameListener(new InternalFrameListener() {
            public void internalFrameOpened(InternalFrameEvent e) {}
            public void internalFrameClosing(InternalFrameEvent e) {}
            public void internalFrameClosed(InternalFrameEvent e) {
                updateTableBancos();
            }
            public void internalFrameIconified(InternalFrameEvent e) {}
            public void internalFrameDeiconified(InternalFrameEvent e) {}
            public void internalFrameActivated(InternalFrameEvent e) {}
            public void internalFrameDeactivated(InternalFrameEvent e) {}
        });
}//GEN-LAST:event_tableBancosMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalBancos;
    private javax.swing.JTable tableBancos;
    // End of variables declaration//GEN-END:variables
}
