/*
 * FrameEstabelecimentoConsulta.java
 *
 * Created on September 30, 2008, 11:05 AM
 */
package org.ai.forms.ambiente.estabelecimentos;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableModel;

import org.ai.bo.ambiente.Estabelecimento;
import org.ai.forms.FormMenuPrincipal;
import org.ai.forms.ambiente.clientes.FrameClienteCadastro;
import org.ai.forms.utils.ColumnResizer;

/**
 *
 * @author  Edison
 */
public class FrameEstabelecimentoConsulta extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private List<Estabelecimento> listEstabelecimentos;
    private DefaultTableModel modelEstabelecimentos;
    Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
    FormMenuPrincipal formPrincipal;

    /** Creates new form FrameEstabelecimentoConsulta
     * @param formPrincipal 
     */
    public FrameEstabelecimentoConsulta(FormMenuPrincipal formPrincipal) {
        initComponents();
        this.formPrincipal = formPrincipal;
        updateTableEstabelecimentos();
    }

    public void updateTableEstabelecimentos() {
        updateListEstabelecimentos();
        tableEstabelecimentos.setModel(modelEstabelecimentos);
        tableEstabelecimentos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableEstabelecimentos.setRowSelectionAllowed(true);
        tableEstabelecimentos.setColumnSelectionAllowed(false);
        ColumnResizer.adjustColumnPreferredWidths(tableEstabelecimentos);
        tableEstabelecimentos.revalidate();
        lblTotalEstabelecimentos.setText(Integer.toString(listEstabelecimentos.size()));

    }

    private void updateListEstabelecimentos() {
        listEstabelecimentos = Estabelecimento.findAll();
        String[] collumnNames = new String[]{"Nome", "Cidade", "Ramo", "POS", "TR"};
        String[][] data = new String[listEstabelecimentos.size()][3];
        for (int i = 0; i < listEstabelecimentos.size(); i++) {
            data[i] = new String[]{
                        listEstabelecimentos.get(i).getNome(),
                        listEstabelecimentos.get(i).getCidade().getNome(),
                        listEstabelecimentos.get(i).getRamoAtividade().getNome(),
                        Integer.toString(listEstabelecimentos.get(i).getTerminaisPOS().size()),
                        Integer.toString(listEstabelecimentos.get(i).getCountTransacoes())
                    };
        }
        modelEstabelecimentos = new DefaultTableModel(data, collumnNames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEstabelecimentos = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalEstabelecimentos = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Consulta de Estabelecimento");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/industry_16.png"))); // NOI18N

        tableEstabelecimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEstabelecimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEstabelecimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEstabelecimentos);

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/Symbol Delete 2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de Estabelecimentos: ");

        lblTotalEstabelecimentos.setText("total");

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/facear/tcc/forms/resources/industry_add_16.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalEstabelecimentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalEstabelecimentos)
                    .addComponent(btnCadastrar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    dispose();
}//GEN-LAST:event_btnFecharActionPerformed

private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    FrameEstabelecimentoCadastro frame = new FrameEstabelecimentoCadastro();
    formPrincipal.getDesktopPane().add(frame);
    frame.setLocation((int) this.getBounds().getX() - frame.getWidth(), (int) this.getBounds().getY());
    frame.setVisible(true);
    frame.addInternalFrameListener(new InternalFrameListener() {
        public void internalFrameOpened(InternalFrameEvent e) {}
        public void internalFrameClosing(InternalFrameEvent e) {}
        public void internalFrameClosed(InternalFrameEvent e) {
            updateTableEstabelecimentos();
        }
        public void internalFrameIconified(InternalFrameEvent e) {}
        public void internalFrameDeiconified(InternalFrameEvent e) {}
        public void internalFrameActivated(InternalFrameEvent e) {}
        public void internalFrameDeactivated(InternalFrameEvent e) {}
    });
}//GEN-LAST:event_btnCadastrarActionPerformed

private void tableEstabelecimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEstabelecimentosMouseClicked
    if (tableEstabelecimentos.getSelectedRow() >= 0){
        Estabelecimento estabelecimento = listEstabelecimentos.get(tableEstabelecimentos.getSelectedRow());
        FrameEstabelecimentoManutencao frame = new FrameEstabelecimentoManutencao(formPrincipal, estabelecimento.getId());
        formPrincipal.getDesktopPane().add(frame);
        frame.setLocation((int) this.getBounds().getX() + this.getWidth(), (int) this.getBounds().getY());
        frame.setVisible(true);
        frame.addInternalFrameListener(new InternalFrameListener() {
            public void internalFrameOpened(InternalFrameEvent e) {}
            public void internalFrameClosing(InternalFrameEvent e) {}
            public void internalFrameClosed(InternalFrameEvent e) {
                updateTableEstabelecimentos();
            }
            public void internalFrameIconified(InternalFrameEvent e) {}
            public void internalFrameDeiconified(InternalFrameEvent e) {}
            public void internalFrameActivated(InternalFrameEvent e) {}
            public void internalFrameDeactivated(InternalFrameEvent e) {}
        });
    }
}//GEN-LAST:event_tableEstabelecimentosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalEstabelecimentos;
    private javax.swing.JTable tableEstabelecimentos;
    // End of variables declaration//GEN-END:variables
}
